export const ACTIONS = {
    // global action
    "SET_MATCH_SCORE_CARD_OPEN": "SET_MATCH_SCORE_CARD_OPEN",
    "SET_EXPERT_MENTION_CARD_OPEN": "SET_EXPERT_MENTION_CARD_OPEN",
    "SET_MAP_CLUSTERS_DATA": "SET_MAP_CLUSTERS_DATA",
    "SET_MAP_VISIBLE": "SET_MAP_VISIBLE",
    "SET_LEFT_MENU_VISIBLE": "SET_LEFT_MENU_VISIBLE",
    "SET_FROM_DATE_STAYS": "SET_FROM_DATE_STAYS",
    "SET_TO_DATE_STAYS": "SET_TO_DATE_STAYS",
    "SET_CODE_STRING": "SET_CODE_STRING",
    "SET_TRIP_SEARCH_STRING": "SET_TRIP_SEARCH_STRING",


    // Hotel Details Page
    "SET_SELECTED_HOTEL_ROOM": "SET_SELECTED_HOTEL_ROOM",
    "SET_SELECTED_HOTEL": "SET_SELECTED_HOTEL",
    "SET_SELECTED_HOTEL_ROOM_PRICING": "SET_SELECTED_HOTEL_ROOM_PRICING",

    //checkout cart
    "ADD_CHECKOUT_CART": "ADD_CHECKOUT_CART",
    "UPDATE_CHECKOUT_CART": "UPDATE_CHECKOUT_CART",
    "UPDATE_TRAVELLER_INFO": "UPDATE_TRAVELLER_INFO",

    //restaurant Page
    "SET_RESTAURANT_DATA_RESET": "SET_RESTAURANT_DATA_RESET"
}